version: '3.3'
services:
  jekyll:
    volumes:
        - './:/srv/jekyll'
    # neede dto add UID or failing with permissionsproblem
    environment:
      JEKYLL_UID: 501
      JEKYLL_GID: 20
    ports:
        - '4000:4000'
        - '35729:35729'
    image: jekyll/jekyll
    command: jekyll serve --incremental --livereload --force_polling
